# Module 02 : Multivariate Linear Regression

*Summary: Building on what you did on the previous modules you will extend the linear
regression to handle more than one features. Then you will see how to build polynomial
models and how to detect overfitting.*

## Notions of the module
Multivariate linear hypothesis, multivariate linear gradient descent, polynomial models. 
Training and test sets, overfitting.

## Useful Ressources  
  
You are strongly advise to use the following resource:
[Machine Learning MOOC - Stanford](https://www.coursera.org/learn/machine-learning/home/week/2)  
Here are the sections of the MOOC that are relevant for today's exercises: 

### Week 2: 

**Multivariate Linear Regression:**
* Multiple Features (Video + Reading)
* Gradient Descent for Multiple Variables (Video + Reading)
* Gradient Descent in Practice I- Feature Scaling (Video + Reading)
* Gradient Descent in Practice II- Learning Rate (Video + Reading)
* Features and Polynomial Regression (Video + Reading)
* Review (Reading + Quiz)

## General rules
See directly the 42Paris intra subject or the corresponding repository on the [github of 42AI](https://github.com/42-AI/bootcamp_machine-learning)


## Helper

Ensure that you have the right Python interpreter (at least 3.7).

## Exercise 00 - Multivariate Hypothesis - Iterative Version

In [1]:
from ex00.prediction import simple_predict
import numpy as np

x = np.arange(1,13).reshape((4,3))
print("# Example 0:")
theta1 = np.array([[5],[0],[0],[0]])
pred = simple_predict(x, theta1)
# Ouput:
# array([[5.],[ 5.],[ 5.],[ 5.]])
# Do you understand why y_hat contains only 5’s here?
expected_pred = np.array([[5.],[ 5.],[ 5.],[ 5.]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), pred.reshape(1, -1))


print("\n# Example 1:")
theta2 = np.array([[0],[1],[0],[0]])
pred = simple_predict(x, theta2)
# Output:
# array([[ 1.],[ 4.],[ 7.],[ 10.]])
# Do you understand why y_hat == x[:,0] here?
expected_pred = np.array([[ 1.],[ 4.],[ 7.],[ 10.]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))


print("\n# Example 2:")
theta3 = np.array([[-1.5],[0.6],[2.3],[1.98]])
pred = simple_predict(x, theta3)
# Output:
# array([[ 9.64],[ 24.28],[ 38.92],[ 53.56]])
expected_pred = np.array([[ 9.64],[ 24.28],[ 38.92],[ 53.56]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))


print("\n# Example 3:")
theta4 = np.array([[-3],[1],[2],[3.5]])
pred = simple_predict(x, theta4)
# Output:
# array([[12.5],[ 32. ],[ 51.5],[ 71. ]])
expected_pred = np.array([[12.5],[ 32. ],[ 51.5],[ 71. ]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

# Example 0:
my prediction:            [[5. 5. 5. 5.]]
expected prediction:      [[5. 5. 5. 5.]]

# Example 1:
my prediction:            [[ 1.  4.  7. 10.]]
expected prediction:      [[ 1.  4.  7. 10.]]

# Example 2:
my prediction:            [[ 9.64 24.28 38.92 53.56]]
expected prediction:      [[ 9.64 24.28 38.92 53.56]]

# Example 3:
my prediction:            [[12.5 32.  51.5 71. ]]
expected prediction:      [[12.5 32.  51.5 71. ]]


## Exercise 01 - Mulltivariate hypothesis - Vectorized Version

In [3]:
import numpy as np
from ex01.prediction import predict_

x = np.arange(1,13).reshape((4,-3))
# Example 0:
theta1 = np.array([[5],[ 0],[ 0],[ 0]])
pred = predict_(x, theta1)
# Ouput:
# array([[5.],[ 5.],[ 5.],[ 5.]])
# Do you understand why y_hat contains only 5’s here?
expected_pred = np.array([[5.],[ 5.],[ 5.],[ 5.]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

# Example 1:
theta2 = np.array([[0],[ 1],[ 0],[ 0]])
pred = predict_(x, theta2)
# Output:
# array([[ 1.],[ 4.],[ 7.],[ 10.]])
# Do you understand why y_hat == x[:,0] here?
expected_pred = np.array([ 1.],[ 4.],[ 7.],[ 10.]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

# Example 2:
theta3 = np.array([[-1.5],[ 0.6],[ 2.3],[ 1.98]])
pred = predict_(x, theta3)
# Output:
# array([[ 9.64],[ 24.28],[ 38.92],[ 53.56]])
expected_pred = np.array([[ 9.64],[ 24.28],[ 38.92],[ 53.56]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

# Example 3:
theta4 = np.array([[-3],[ 1],[ 2],[ 3.5]])
pred = predict_(x, theta4)
# Output:
# array([[12.5],[ 32. ],[ 51.5],[ 71. ]])
expected_pred = np.array([[12.5],[ 32. ],[ 51.5],[ 71. ]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

my prediction:            [[5. 5. 5. 5.]]
expected prediction:      [[5. 5. 5. 5.]]


TypeError: array() missing required argument 'object' (pos 0)

## Exercise 02 - Vectorized Loss Function

## Exercise 03 - Multivariate Gradient

## Exercise 04 - Multivariate Gradient Descent

## Exercise 05 - Multivariate Linear Regression With Class

## Exercise 06 - Practicing Multivariate Linear Regression

## Exercise 07 - Polynommial models

## Exercise 08 - Let's Train Polynomial Models!

## Exercise 09 - DataSpliter

## Exercise 10 - Machine Learning for Grown-ups: Training and Test Sets